# Generated by Django 5.0.4 on 2024-05-08 08:41

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="complete",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 8, 8, 35, 33, 183445, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="important",
            field=models.BooleanField(default=True),
        ),
    ]
